version: "3"
services:
    frontend:
        container_name: r-ecommerce-client
        build: ./client
        ports:
        - 4000:3000
        volumes:
        - ./client:/home/app/client
        depends_on:
        - backend

    backend:
        container_name: r-ecommerce-api
        build: ./api
        ports:
        - 4001:3001
        volumes:
        - ./api:/home/app/api
        depends_on:
        - db

    db:
        container_name: r-ecommerce-db
        image: mysql:5.7.22
        environment: 
            MYSQL_DATABASE:: "r-ecommerce"
            MYSQL_USER:  "root"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
        restart: always
        ports:
          - 13306:3306
        volumes:
        - ./db:/var/lib/mysql
