version: "3"
services:
    frontend:
        container_name: r-ecommerce-client
        build: ./client
        ports:
        - 13000:3000
        volumes:
        - ./client:/home/app/client
        depends_on:
        - backend

    backend:
        container_name: r-ecommerce-api
        build: ./api
        ports:
        - 13001:3001
        volumes:
        - ./api:/home/app/api
        depends_on:
        - db

    db:
        container_name: r-ecommerce-db
        image: postgres:9.6.24
        environment: 
            POSTGRES_DB: "r-ecommerce"
            POSTGRES_USER:  "postgres"
            POSTGRES_PASSWORD: "#Postgres123"
        restart: always
        ports:
          - 15432:5432
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
